version: "3.8"

services:
  backend:
    ports:
      - "5005:5005"   # JVM debug port
    environment:
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
